### ISSUE TITLE
Investigación de librerías y especificación de caso de uso que intervenga un QR

### ISSUE THREAD

**Issue by zenoma** [dfr99/SwimChrono#19]
### Motivación

Es recomendable que exista una integración con la cámara. Para ello vamos a crear QR unívocos para cada persona que tenga acceso a la aplicación. La propia aplicación también tiene que poder leer esos QR.

### Criterios de aceptación

- [ ] Especificación concreta del caso de uso. La creación de un QR por cada persona sería un caso de uso. Otro posible caso de uso sería confirmar acceso en una competición de un nadador, o vinculación del árbitro con una calle a la hora de la toma de tiempos.
- [ ] Investigación de librerías o herramientas para la realización de esa integración
- [ ] Actualización del dominio de la aplicación para que quede reflejado el/los nuevos casos de uso

**Comment by dfr99** [comment]
Añadir documentación relacionada con las integraciones bajo el directorio `docs/integrations`
