### ISSUE TITLE
Creación dinámica de QR

### ISSUE THREAD

**Issue by zenoma** [dfr99/SwimChrono#77]
### Motivación

Cada usuario debe tener un QR, creado a partir de la información única del usuario.

### Criterios de aceptación

- [x] El apartado de Mi QR debe generar el QR del usuario.
- [x] El uso de la librería y alguna información relevante debe estar reflejada en la Wiki

**Comment by AlejandroRVaquero** [comment]
Issue cerrada desde aqui
